### ISSUE TITLE
new version released Flare 1.02

### ISSUE THREAD

**Issue by pixelr0** [mcphail/flare#1]
so yeah :D Flare 1.02 http://flarerpg.org/index.php/2018/04/05/flare-1-02/

**Comment by mcphail** [comment]
Cheers. I'm away from civilisation for a while so can't test this. I've set up a 1.02 build which should hit the `--edge` channel in half an hour or so. Let me know if it works for you.

**Comment by pixelr0** [comment]
works fine! :D 
thanks o/
