### ISSUE TITLE
Flare 1.07 released

### ISSUE THREAD

**Issue by pixelr0** [mcphail/flare#3]
Flare 1.07
http://flarerpg.org/index.php/2018/08/31/flare-1-07/

**Comment by pixelr0** [comment]
would be nice the upstream to adopt the snap so you don't have to maintain them snap :/

**Comment by mcphail** [comment]
Thanks again. I'll have a look.

It'd be nice to submit this upstream, but I haven't thought of a reliable way to deal with automatically building from the 2 repos, for the game and the engine. Building manually, I can check they're both at the same release number.

**Comment by mcphail** [comment]
That's the new version in stable. It prints an error message on first run about changed key bindings but I think it is trivial enough to not annoy users too much...
