### ISSUE TITLE
Flare 1.09 released

### ISSUE THREAD

**Issue by dorkster** [mcphail/flare#4]
http://flarerpg.org/index.php/2018/12/09/flare-1-09/

**Comment by mcphail** [comment]
Ah, thanks @dorkster. I'd missed this as the project had changed ownership on github. I'll build one just now and test.

**Comment by dorkster** [comment]
Thanks!

**Comment by dorkster** [comment]
Sorry to bother you again, but I just pushed a [quick fix update](http://flarerpg.org/index.php/2018/12/12/flare-1-09-01/) for a crash that was occurring with the Flatpak version of Flare. I'm not sure if the Snap was affected, but I'd recommend updating just in case.

**Comment by mcphail** [comment]
Thanks. I'm building a version for the edge channel. I'll promote it to stable tomorrow when I get a chance to test it. I appreciate your help.
